sudo: false
cache: bundler
language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
  - jruby
gemfile:
  - gemfiles/Gemfile.rails-4-0-stable
  - gemfiles/Gemfile.rails-4-1-stable
  - gemfiles/Gemfile.rails-4-2-stable
  - gemfiles/Gemfile.rails-5-0-stable
  - gemfiles/Gemfile.rails-5-1-stable
  - Gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1.10
      gemfile: Gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/Gemfile.rails-4-1-stable # activesupport 4.1 depends on json 1.8.3 which does not compile with Ruby 2.4.0
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.rails-4-1-stable # activesupport 4.1 depends on json 1.8.3 which does not compile with Ruby 2.4.0
    - rvm: jruby
      gemfile: Gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-5-0-stable
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5-0-stable
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5-0-stable
    - rvm: jruby
      gemfile: gemfiles/Gemfile.rails-5-0-stable
    - rvm: jruby
      gemfile: gemfiles/Gemfile.rails-5-1-stable # rack 2.0.1 requires Ruby version >= 2.2.2; any sol'n for jruby?
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-5-1-stable # rack 2.0.1 requires Ruby version >= 2.2.2
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5-1-stable # rack 2.0.1 requires Ruby version >= 2.2.2
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5-1-stable # rack 2.0.1 requires Ruby version >= 2.2.2
notifications:
  email: false
  slack:
    on_pull_requests: false
    on_success: change
    on_failure: always
    secure: vxwuYTr2Sy+a/C7VP06l3QQCSgsKH7mjbTqOF1cKfGgmIHwO2p1VZmNCKjOe24ILj090WmVfHdnF/MnSCQw/SD1mVNbCZFf8Vj7+fYBu26I7BfahN0jxv3S5NO1sx4ipj0cO17r21OjtD2r1XzOfKqdSkjBBCOk8+WjiqtmCXII=
